steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/generated-arena-325607/ixh-auth-repos', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/generated-arena-325607/ixh-auth-repos']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'redis-deployment.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=abhi-staging'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'node-deployment.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=abhi-staging'
timeout: 500s
options:
  logging: CLOUD_LOGGING_ONLY
images: ['asia.gcr.io/generated-arena-325607/ixh-auth-repos']