steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/generated-arena-325607/ixh-auth-repos:v1', '.']
  timeout: 500s

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/generated-arena-325607/ixh-auth-repos:v1']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'redis-deployment.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=abhi-prod'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'node-deployment.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=abhi-prod'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'node-service.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=abhi-prod'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['rollout', 'restart', 'deployment', 'ixh-auth-depl']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=abhi-prod'
timeout: 500s

options:
  logging: CLOUD_LOGGING_ONLY
images: ['us.gcr.io/generated-arena-325607/ixh-auth-repos:v1']