apiVersion: apps/v1
kind: Deployment
metadata:
  name: ixh-auth-depl
  labels:
    app: ixh-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ixh-auth
  template:
    metadata:
      labels:
        app: ixh-auth
    spec:
      containers:
      - name: ixh-auth
        image: asia.gcr.io/generated-arena-325607/ixh-auth-repos:staging
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m




